"""Approval request model -- the human-in-the-loop record.

This table is the security boundary between "the model proposed an action" and
"the action happened". The row stores the *exact* arguments a human was shown,
plus a SHA-256 digest of them. Execution re-derives the digest from the stored
arguments and refuses to run if it does not match, so a mutated payload can never
ride on an approval that was granted for something else.

Nothing here trusts the model: the LLM cannot create, approve or expire a row --
only :mod:`app.services.approval_service` can, and only via guarded transitions.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.security import verify_payload
from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin
from app.db.types import JSONColumn, UTCDateTime
from app.models.database.enums import ApprovalStatus, PermissionLevel, str_enum_column

if TYPE_CHECKING:
    from app.models.database.user import User

#: Statuses from which no further transition is possible.
TERMINAL_APPROVAL_STATUSES: frozenset[ApprovalStatus] = frozenset(
    {
        ApprovalStatus.REJECTED,
        ApprovalStatus.EXPIRED,
        ApprovalStatus.EXECUTED,
        ApprovalStatus.FAILED,
    }
)


class ApprovalRequest(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A proposed high-risk action awaiting a human decision."""

    __tablename__ = "approval_requests"
    __table_args__ = (
        Index("ix_approval_requests_status_expires", "status", "expires_at"),
        Index("ix_approval_requests_conversation_status", "conversation_id", "status"),
    )

    conversation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("conversations.id", ondelete="CASCADE"), index=True, nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )

    # --- what was proposed -------------------------------------------------- #
    tool_name: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    server_name: Mapped[str] = mapped_column(String(64), nullable=False)
    arguments: Mapped[dict[str, Any]] = mapped_column(JSONColumn, nullable=False)
    arguments_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    permission_level: Mapped[PermissionLevel] = mapped_column(
        str_enum_column(PermissionLevel, "permission_level"), nullable=False
    )
    #: Plain-language description shown to the approver. Generated by backend code
    #: from the tool name and arguments -- never free-form text from the model.
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    risk_reason: Mapped[str] = mapped_column(Text, nullable=False)
    tool_call_id: Mapped[str | None] = mapped_column(String(128), index=True)

    # --- lifecycle ---------------------------------------------------------- #
    status: Mapped[ApprovalStatus] = mapped_column(
        str_enum_column(ApprovalStatus, "approval_status"),
        default=ApprovalStatus.PENDING,
        nullable=False,
        index=True,
    )
    expires_at: Mapped[datetime] = mapped_column(UTCDateTime, nullable=False, index=True)
    decided_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    decided_by_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    decision_note: Mapped[str | None] = mapped_column(Text)

    # --- outcome ------------------------------------------------------------ #
    executed_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    execution_result: Mapped[dict[str, Any] | None] = mapped_column(JSONColumn)
    error: Mapped[str | None] = mapped_column(Text)

    user: Mapped[User] = relationship(
        back_populates="approval_requests", foreign_keys=[user_id], lazy="selectin"
    )

    # ------------------------------------------------------------------ logic --
    def is_expired(self, now: datetime | None = None) -> bool:
        expires = self.expires_at if self.expires_at.tzinfo else self.expires_at.replace(tzinfo=UTC)
        return expires <= (now or datetime.now(UTC))

    @property
    def is_terminal(self) -> bool:
        return self.status in TERMINAL_APPROVAL_STATUSES

    @property
    def is_actionable(self) -> bool:
        """Pending and still within its TTL."""
        return self.status == ApprovalStatus.PENDING and not self.is_expired()

    def verify_integrity(self) -> bool:
        """Confirm the stored arguments still match the digest recorded at creation."""
        return verify_payload(self.arguments, self.arguments_hash)
